// src/app/layout.tsx
// This file is used to wrap the entire application with a layout component. This is useful for adding global styles, context providers, or other components that should be rendered on every page.
import type { Metadata } from "next";
import "./globals.css";
import AuthContext from '@/app/context/AuthContext';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="antialiased" suppressHydrationWarning>
        <AuthContext>
          {children}
        </AuthContext>
      </body>
    </html>
  )
}
